### ISSUE TITLE
Deploy interchain accounts to testnet3

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#1352]
Alternatively, repoint existing app to testnet3 mailboxes

**Comment by yorhodes** [comment]
```
DEBUG=* yarn ts-node scripts/middleware/deploy-accounts.ts --environment testnet3 --context hyperlane
Merge artifacts complete
Error: file doesn't exist at config/environments/testnet3/middleware/accounts/addresses.json
    at readFileAtPath (/Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/utils/utils.ts:167:11)
    at readJSONAtPath (/Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/utils/utils.ts:173:21)
    at readJSON (/Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/utils/utils.ts:177:10)
    at /Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/deploy.ts:19:31
    at Generator.next (<anonymous>)
    at /Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/deploy.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/deploy.ts:4:12)
    at deployWithArtifacts (/Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/src/deploy.ts:16:12)
    at /Users/yorhodes/hyperlane/abacus-monorepo/typescript/infra/scripts/middleware/deploy-accounts.ts:45:28
  hyperlane:RouterDeployer Start deploy to alfajores,fuji,mumbai,bsctestnet,goerli,moonbasealpha,optimismgoerli,arbitrumgoerli +0ms
  hyperlane:RouterDeployer Deploying to alfajores from https://alfajores.celoscan.io/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on alfajores +1ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +226ms
  hyperlane:ChainConnection Pending https://alfajores.celoscan.io/tx/0xe6753f4671c461396ee22f01d8a633841d950753918d670e07a99126a11abd7d (waiting 1 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +7s
  hyperlane:RouterDeployer Deploying to fuji from https://testnet.snowtrace.io/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on fuji +1ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +192ms
  hyperlane:ChainConnection Pending https://testnet.snowtrace.io/tx/0x3e05b45e86c181d1b48338194eba4491b2dc8d2667453a447d3f6ef3a73085f7 (waiting 3 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +10s
  hyperlane:RouterDeployer Deploying to mumbai from https://mumbai.polygonscan.com/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on mumbai +2ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +214ms
  hyperlane:ChainConnection Pending https://mumbai.polygonscan.com/tx/0xb643e3320b44192b6d868a522451df6346a0f9a8756c7c99002e79231250e617 (waiting 3 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +14s
  hyperlane:RouterDeployer Deploying to bsctestnet from https://testnet.bscscan.com/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on bsctestnet +2ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +1s
  hyperlane:ChainConnection Pending https://testnet.bscscan.com/tx/0xb36db4d817e152a75e301edb19047146928178335dbfd7bd053a1192fc57fc45 (waiting 1 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +13s
  hyperlane:RouterDeployer Deploying to goerli from https://goerli.etherscan.io/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on goerli +2ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +134ms
  hyperlane:ChainConnection Pending https://goerli.etherscan.io/tx/0xe255bf1b5df978ecb6156ec6da1e33ce5daa0ecef90acfea4bce72949845013d (waiting 1 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +17s
  hyperlane:RouterDeployer Deploying to moonbasealpha from https://moonbase.moonscan.io/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on moonbasealpha +2ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +301ms
  hyperlane:ChainConnection Pending https://moonbase.moonscan.io/tx/0x61ab01e3be455e33da32c2ff04b65657fc18eb583501c4a2e05e3cb1c9c2d3bc (waiting 1 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +23s
  hyperlane:RouterDeployer Deploying to optimismgoerli from https://goerli-optimism.etherscan.io/address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on optimismgoerli +2ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +231ms
  hyperlane:ChainConnection Pending https://goerli-optimism.etherscan.io/tx/0x131359257aec8a6fabd0517048a3f9dc6e72e1ce131dd48dd06471a90c12069b (waiting 1 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +7s
  hyperlane:RouterDeployer Deploying to arbitrumgoerli from https://goerli.arbiscan.io//address/0xfaD1C94469700833717Fa8a3017278BC1cA8031C ... +0ms
  hyperlane:RouterDeployer Deploy router on arbitrumgoerli +1ms
  hyperlane:RouterDeployer Deploying with CREATE2 factory +613ms
  hyperlane:ChainConnection Pending https://goerli.arbiscan.io//tx/0x69a5f3ea9edee6a677f4eab652d504c4ac3a33912b52414ea957e35cb1fd8169 (waiting 1 blocks for confirmation) +0ms
  hyperlane:RouterDeployer {
  hyperlane:RouterDeployer   "router": "0xdf8499B68A392D08B748a8B072cA365826ac0091"
  hyperlane:RouterDeployer } +4s
  hyperlane:RouterDeployer Enrolling deployed routers with each other (if not already)... +5ms
  hyperlane:RouterDeployer { local: 'alfajores' } +0ms
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +759ms
  hyperlane:RouterDeployer Enroll remote (fuji,mumbai,bsctestnet,goerli,moonbasealpha,optimismgoerli,arbitrumgoerli) routers on alfajores +2ms
  hyperlane:ChainConnection Pending https://alfajores.celoscan.io/tx/0xf1b54ae10bde662fb1d67dd97b84b2384c1b99e035f570de5cd5236a47ff359a (waiting 1 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'fuji' } +7s
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +559ms
  hyperlane:RouterDeployer Enroll remote (alfajores,mumbai,bsctestnet,goerli,moonbasealpha,optimismgoerli,arbitrumgoerli) routers on fuji +1ms
  hyperlane:ChainConnection Pending https://testnet.snowtrace.io/tx/0x5891b36d15e4cdb85d42896342cfe4df8ffc833bf47d33d104ec639ebd53326d (waiting 3 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'mumbai' } +10s
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +841ms
  hyperlane:RouterDeployer Enroll remote (alfajores,fuji,bsctestnet,goerli,moonbasealpha,optimismgoerli,arbitrumgoerli) routers on mumbai +1ms
  hyperlane:ChainConnection Pending https://mumbai.polygonscan.com/tx/0x7dcd25938dfd40f75aa4033d5ff6229c9d66e5ed0a7a42097004686dd5ae208e (waiting 3 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'bsctestnet' } +14s
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +18s
  hyperlane:RouterDeployer Enroll remote (alfajores,fuji,mumbai,goerli,moonbasealpha,optimismgoerli,arbitrumgoerli) routers on bsctestnet +0ms
  hyperlane:ChainConnection Pending https://testnet.bscscan.com/tx/0x4bc65dfaf96ee8cc9a2f0fdcec1d5e2c607d98ebaba9c2c92f3ffd8f8a38f78d (waiting 1 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'goerli' } +18s
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +256ms
  hyperlane:RouterDeployer Enroll remote (alfajores,fuji,mumbai,bsctestnet,moonbasealpha,optimismgoerli,arbitrumgoerli) routers on goerli +0ms
  hyperlane:ChainConnection Pending https://goerli.etherscan.io/tx/0x01803a247452be6274dcfec55c4666b9b58baf750d8616f007270cf76c6b2a99 (waiting 1 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'moonbasealpha' } +29s                                                                          hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +1s
  hyperlane:RouterDeployer Enroll remote (alfajores,fuji,mumbai,bsctestnet,goerli,optimismgoerli,arbitrumgoerli) routers on moonbasealpha +1ms
  hyperlane:ChainConnection Pending https://moonbase.moonscan.io/tx/0x9a567328b8aa4c198d4c2abf3de9a583019c04f3c60c10c8b38ff267fd82af5a (waiting 1 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'optimismgoerli' } +27s
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +450ms
  hyperlane:RouterDeployer Enroll remote (alfajores,fuji,mumbai,bsctestnet,goerli,moonbasealpha,arbitrumgoerli) routers on optimismgoerli +0ms
  hyperlane:ChainConnection Pending https://goerli-optimism.etherscan.io/tx/0xf5d8186408e1a5bb57b8192d1f6c20c742cbb5e76476e3136ad939de4f529c54 (waiting 1 blocks for confirmation) +2m
  hyperlane:RouterDeployer { local: 'arbitrumgoerli' } +6s
  hyperlane:RouterDeployer Owner and signer are equal, proceeding {
  owner: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C',
  signer: '0xfaD1C94469700833717Fa8a3017278BC1cA8031C'
} +443ms
  hyperlane:RouterDeployer Enroll remote (alfajores,fuji,mumbai,bsctestnet,goerli,moonbasealpha,optimismgoerli) routers on arbitrumgoerli +0ms
  hyperlane:ChainConnection Pending https://goerli.arbiscan.io//tx/0x1577ebfb3fec5f667c544d9a7be553a7b66db640e3a0bbf78f3f3ff6e72d5ba8 (waiting 1 blocks for confirmation) +2m
 ```
