### ISSUE TITLE
Unable to send message

### ISSUE THREAD

**Issue by corymaklin** [hyperlane-xyz/hyperlane-monorepo#4920]
I'm trying to send a basic message from one chain to another, but I can't get it working. The message looks good to me. The configuration is the same as the one in the registry.

```
hyperlane send message --origin sepolia --destination basesepolia --relay --verbosity debug
Hyperlane CLI
(node:42010) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"level":30,"time":1732821654167,"pid":42010,"msg":"Your CLI version: 7.1.0, latest version: 7.2.0"}
Fetching from github: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/chains/metadata.yaml
Running pre-flight checks for chains...
✅ Chains are valid
✅ Signer is valid
✅ Balances are sufficient
Fetching from github: https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/main/chains/addresses.yaml
Dispatching message
Pending https://sepolia.etherscan.io/tx/0xaca49ac9d9ca2c135e599d7904261ace15ca54472aaa2158b43c1c8df7097eb6 (waiting 1 blocks for confirmation)


Sent message from sepolia to 0x783c4a0bB6663359281aD4a637D5af68F83ae213 on basesepolia.
Message ID: 0x5e9e0fb9fe207a4158c6594510450ea0ebe44ed3dd2bd6e302be08485f5a30fb
Message:
    parsed:
      version: 3
      nonce: 839430
      origin: 11155111
      sender: "0x000000000000000000000000ce540c76da43a46a5a02a5680dfda907b8fa3d1a"
      destination: 84532
      recipient: "0x000000000000000000000000783c4a0bb6663359281ad4a637d5af68f83ae213"
      body: "0x48656c6c6f21"
      originChain: sepolia
      destinationChain: basesepolia
    id: "0x5e9e0fb9fe207a4158c6594510450ea0ebe44ed3dd2bd6e302be08485f5a30fb"
    message: "0x03000ccf0600aa36a7000000000000000000000000ce540c76da43a46a5a02a5680\
      dfda907b8fa3d1a00014a34000000000000000000000000783c4a0bb6663359281ad4a637d5af\
      68f83ae21348656c6c6f21"
    
Received 0x result from call for reqId 22.
{
  error: Error: Invalid response from provider
      at HyperlaneJsonRpcProvider.perform (file:///Users/cmaklin/.nvm/versions/node/v22.11.0/lib/node_modules/@hyperlane-xyz/cli/node_modules/@hyperlane-xyz/sdk/dist/providers/SmartProvider/HyperlaneJsonRpcProvider.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async HyperlaneSmartProvider.wrapProviderPerform (file:///Users/cmaklin/.nvm/versions/node/v22.11.0/lib/node_modules/@hyperlane-xyz/cli/node_modules/@hyperlane-xyz/sdk/dist/providers/SmartProvider/SmartProvider.js:247:28)
      at async HyperlaneSmartProvider.performWithFallback (file:///Users/cmaklin/.nvm/versions/node/v22.11.0/lib/node_modules/@hyperlane-xyz/cli/node_modules/@hyperlane-xyz/sdk/dist/providers/SmartProvider/SmartProvider.js:191:32)
      at async retryAsync (file:///Users/cmaklin/.nvm/versions/node/v22.11.0/lib/node_modules/@hyperlane-xyz/cli/node_modules/@hyperlane-xyz/utils/dist/async.js:77:28),
  providerIndex: 0,
  rpcUrl: 'https://ethereum-sepolia.publicnode.com',
  method: 'call({"transaction":{"to":"0xce540c76DA43a46a5A02A5680DFDA907b8Fa3d1A","data":"0x7f5a7c7b","accessList":null},"blockTag":"latest"})',
  chainId: 11155111
} Error from provider.
```

**Comment by yorhodes** [comment]
hey @corymaklin , thanks for reporting this

I believe this is due to a legacy issue only affecting the `sepolia` deployment
can you try sending the other direction ie 
`hyperlane send message --origin basesepolia --destination sepolia --relay`

**Comment by jmrossy** [comment]
No response on this for about 2 months. Closing for now.
